package com.ronit.dao;

import java.util.List;

import com.ronit.beans.Company;
import com.ronit.beans.Coupon;
import com.ronit.enums.Category;
import com.ronit.exceptions.CouponSystemException;

public interface CompaniesDao {
	
	/**
	 * isCouponExistsByCompanyIdAndTitle - checks if a coupon exists in the db,
	 * by companyID and coupon title
	 *  getOneCustomer - get a customer's details from the db, by customerID
	 * @param customerID, email,password
	 * @throws CouponSystemException
	 */
	boolean isCouponExistsByCompanyIdAndTitle(int companyID, String title) throws CouponSystemException;
	boolean isCompanyExistsByName(String name) throws CouponSystemException;
	boolean isCompanyExistsByEmail(String email) throws CouponSystemException;
	boolean isCompanyExistsByEmailAndPassword(String email, String password) throws CouponSystemException;
	Company getCompanyByEmailAndPassword(String email, String password) throws CouponSystemException;
		
	/**
	 * @param company - the company to add to the db
	 * @return the id of the created company as generated by the data source
	 * @throws CouponSystemException
	 */
	int addCompany(Company company) throws CouponSystemException;
	List<Coupon> getCompanyCoupons(int companyId, Category category) throws CouponSystemException;
	List<Coupon> getCompanyCoupons(int companyId, double maxPrice) throws CouponSystemException;
	List<Coupon> getCompanyCoupons(int companyId) throws CouponSystemException;
	void updateCompany(Company company) throws CouponSystemException;
	void deleteCompany(int companyID) throws CouponSystemException;
	List <Company> getAllCompanies() throws CouponSystemException;
	Company getOneCompany(int companyID) throws CouponSystemException;
}
